### ISSUE TITLE
Usage of drep.d_cluster.cluster_hierarchical in API module

### ISSUE THREAD

**Issue by TarsLi** [MrOlm/drep#71]
[fastANI.txt](https://github.com/MrOlm/drep/files/4324390/fastANI.txt)

Dear Matt Olm, 
I encountered a new problem: I try to cluster my genomes using dRep, and I already get the pairwise ANI values using fastANI. How can I construct a symmetric dist matrix for the drep.d_cluster.cluster_hierarchical offerred in API module using my ANI values? I try to convert the dataframe to the numpy matrix, but there is always an errors: Distance matrix 'X' must be symmetric. 
The pairwise ANI values are attached,  i hope you can give me an example! Thanks!

​

**Comment by MrOlm** [comment]
HI Tars,

The method that you're looking for is `make_linkage_Ndb`. This method averages the values between reciprocal comparisons to make the database symmetric, then pivots the table for you.

The method in dRep where this is done is called `genome_hierarchical_clustering` in the `d_cluster.py` file.

Let me know if you have any questions or hit any other snags!

-Matt

**Comment by TarsLi** [comment]
Thanks a lot for your quick reply!
In the second method you provided, how can I call the command and prepare the input file?
Another question is, can i provide a series of cutoffs for the secondary clustering to see the cluster number of the genomes, but only calculate the paired ANI values once? In other words, how to implement calculation one time and call the result multiple times?

Best

**Comment by MrOlm** [comment]
Hi Tars,

If you have your paired ANI values (as loaded from the file `Ndb.csv`, and you subset to a single primary clusters, you can call it following the formula:

`cdb, arguments = genome_hierarchical_clustering(Ndb, **kwargs)`

If you want to run it on all primary cluster, you can do something like

```
    Cdb = pd.DataFrame()
    for name, ndb in Ndb.groupby(id):
        cdb, cluster_ret = genome_hierarchical_clustering(ndb, cluster=name, **kwargs)
        cdb[id] = name
        Cdb = pd.concat([Cdb,cdb], ignore_index=True)
```

You can provide the following arguments to `genome_hierarchical_clustering` to change how the clustering goes:

```
def genome_hierarchical_clustering(Ndb, **kwargs):
    '''
    Cluster ANI database
    Args:
        Ndb: result of secondary clustering
    Keyword arguments:
        clusterAlg: how to cluster the database (default = single)
        S_ani: thershold to cluster at (default = .99)
        cov_thresh: minumum coverage to be included in clustering (default = .5)
        cluster: name of the cluster
        comp_method: comparison algorithm used
    Returns:
        list: [Cdb, {cluster:[linkage, linkage_db, arguments]}]
```

So for example,  
```
for threshold in [0.95, 0.98]:
    cdb, arguments = genome_hierarchical_clustering(Ndb, S_ani=threshold)
```

Best,
Matt
